# Site settings
title: Zhangyw Blog
SEOTitle: 张耀文的博客 | Zhangyw Blog
header-img: img/home-bg.jpg
email: zyw19871007@163.com
description: "客官，来了"
keyword: "Zhangyw Blog, 博客, 个人网站, 互联网, Web"
url: "http://blog.705192166.xyz/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     Zhangyw
zhihu_username:     chang-jiang-kong-zi-liu
github_username:    zyw19871007
#twitter_username:   Zhangyw
#facebook_username:  Zhangyw
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: zyw19871007

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-155064823-1'            # Format: UA-xxxxxx-xx
ga_domain: blog.705192166.xyz



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "hope to keep writing blog"
sidebar-avatar: /img/avatar-my-art.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "google",
        href: "https://google.com"
    }
]
